"""Demo script to POST a test alert to the backend /alerts/send endpoint.
Usage: python demo_send_alert.py
"""
import httpx
import os

URL = os.getenv('MINESHIELD_URL', 'http://localhost:8000')

payload = {
    'level': 'CRITICAL',
    'type': 'Demo Test Alert',
    'message': 'This is a demo critical alert generated by demo_send_alert.py',
    'location': 'Demo Site — Sector X',
    'via': ['email'],
    'dest': os.getenv('DEMO_ALERT_EMAIL', 'ops@example.com')
}

if __name__ == '__main__':
    try:
        r = httpx.post(f"{URL}/alerts/send", json=payload, timeout=10.0)
        print('Status:', r.status_code)
        print('Response:', r.json())
    except Exception as e:
        print('Failed to send demo alert:', e)
